<?php
Yii::app()->clientscript->scriptMap['jquery.js'] = false;
$this->widget("UGridView", array(
	'id'=>'joom_listing_widget',
	'filter'=>$model,
	'dataProvider'=>$model->search(),
	'selectableRows' => 2,
	'columns'=>array(
			array(
					'name'=>'ID',
					'value'=>'$data->id',
					
					'htmlOptions'=>array(
						'style'=>'width:40px',
						'align'=>'center',
					),
					'headerHtmlOptions'=>array(
							'align'=>'center',
							'onclick'=>'',
					),
					
			),
			array(
					'name'=>'sku',
					'value'=>'$data->sku',
					'type'=>'raw',
					'htmlOptions'=>array(
						'style'=>'width:80px'
					),
					'headerHtmlOptions'=>array(
							'align'=>'center'
					),
			),
			array(
					'name'=>'online_sku',
					'value'=>'$data->online_sku',
					'type'=>'raw',
					'htmlOptions'=>array(
							'style'=>'width:150px'
					),
					'headerHtmlOptions'=>array(
							'align'=>'center'
					),
			),
			
			array(
					'name'=>'listing_id',
					'value'=>'$data->listing_id',
					'type'=>'raw',
					'htmlOptions'=>array(
							'style'=>'width:200px'
					),
					'headerHtmlOptions'=>array(
							'align'=>'center'
					),
			),
			array(
					'name'=>'account_id',
					'value'=>'$data->account_id',
					'type'=>'raw',
					'htmlOptions'=>array(
							'style'=>'width:100px'
					),
					'headerHtmlOptions'=>array(
							'align'=>'center'
					),
			),
        array(
            'name'=>'seller_name',
            'value'=>'$data->seller_name',
            'type'=>'raw',
            'htmlOptions'=>array(
                'style'=>'width:100px'
            ),
            'headerHtmlOptions'=>array(
                'align'=>'center'
            ),
        ),
			array(
					'name'=>'upload_status',
					'value'=>'$data->upload_status',
					'type'=>'raw',
					'htmlOptions'=>array(
							'style'=>'width:100px'
					),
					'headerHtmlOptions'=>array(
							'align'=>'center'
					),
			),
        array(
            'name'=>'update_type',
            'value'=>'$data->update_type',
            'type'=>'raw',
            'htmlOptions'=>array(
                'style'=>'width:150px'
            ),
            'headerHtmlOptions'=>array(
                'align'=>'center'
            ),
        ),

        array(
            'name'=>'old_listing_price',
            'value'=>'$data->old_listing_price',
            'type'=>'raw',
            'htmlOptions'=>array(
                'style'=>'width:100px'
            ),
            'headerHtmlOptions'=>array(
                'align'=>'center'
            ),
        ),
        array(
            'name'=>'old_profit_rate',
            'value'=>'$data->old_profit_rate',
            'type'=>'raw',
            'htmlOptions'=>array(
                'style'=>'width:100px'
            ),
            'headerHtmlOptions'=>array(
                'align'=>'center'
            ),
        ),
        array(
            'name'=>'new_listing_price',
            'value'=>'$data->new_listing_price',
            'type'=>'raw',
            'htmlOptions'=>array(
                'style'=>'width:100px'
            ),
            'headerHtmlOptions'=>array(
                'align'=>'center'
            ),
        ),
        array(
            'name'=>'new_profit_rate',
            'value'=>'$data->new_profit_rate',
            'type'=>'raw',
            'htmlOptions'=>array(
                'style'=>'width:100px'
            ),
            'headerHtmlOptions'=>array(
                'align'=>'center'
            ),
        ),
        array(
            'name'=>'upload_times',
            'value'=>'$data->upload_times',
            'type'=>'raw',
            'htmlOptions'=>array(
                'style'=>'width:50px'
            ),
            'headerHtmlOptions'=>array(
                'align'=>'center'
            ),
        ),
			array(
					'name'=>'created_at',
					'value'=>'$data->created_at',
					'type'=>'raw',
					'htmlOptions'=>array(
							'style'=>'width:100px'
					),
					'headerHtmlOptions'=>array(
							'align'=>'center'
					),
			),
        array(
            'name'=>'updated_at',
            'value'=>'$data->updated_at',
            'type'=>'raw',
            'htmlOptions'=>array(
                'style'=>'width:100px'
            ),
            'headerHtmlOptions'=>array(
                'align'=>'center'
            ),
        ),
        array(
            'name'=>'last_user_id',
            'value'=>'$data->last_user_id',
            'type'=>'raw',
            'htmlOptions'=>array(
                'style'=>'width:100px'
            ),
            'headerHtmlOptions'=>array(
                'align'=>'center'
            ),
        ),
			array(
					'name'=>'message',
					'value'=>'$data->message',
					'type'=>'raw',
					'htmlOptions'=>array(
							'style'=>'width:250px'
					),
					'headerHtmlOptions'=>array(
							'align'=>'center'
					),
			),
        array(
            'name'=>'action',
            'value'=>'$data->actionText',
            'type'=>'raw',
            'htmlOptions'=>array(
                'style'=>'width:100px'
            ),
            'headerHtmlOptions'=>array(
                'align'=>'center'
            ),
        ),
			
	),
	'toolBar'=>array(
			
	),
	'pager'=>array(
		
	),
	'tableOptions'=>array(
		'layoutH'	=>	150,
		'tableFormOptions'	=>	true
	)
		
));
?>